// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "smart_house_backend/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// Houses is an autogenerated mock type for the Houses type
type Houses struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, house
func (_m *Houses) Create(ctx context.Context, house domain.House) (string, error) {
	ret := _m.Called(ctx, house)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, domain.House) string); ok {
		r0 = rf(ctx, house)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.House) error); ok {
		r1 = rf(ctx, house)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Houses) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *Houses) Get(ctx context.Context, id string) (domain.House, error) {
	ret := _m.Called(ctx, id)

	var r0 domain.House
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.House); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.House)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, house
func (_m *Houses) Update(ctx context.Context, house domain.House) error {
	ret := _m.Called(ctx, house)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.House) error); ok {
		r0 = rf(ctx, house)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
